/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#131b2e",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed": "#dae2fd",
        "background": "#faf8ff",
        "surface-container": "#ededf9",
        "secondary": "#565e74",
        "surface-bright": "#faf8ff",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed-dim": "#ffb596",
        "surface-variant": "#e1e2ed",
        "on-primary": "#ffffff",
        "outline": "#737686",
        "on-primary-container": "#eeefff",
        "on-secondary-container": "#5c647a",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-surface": "#2e3039",
        "on-error": "#ffffff",
        "surface": "#faf8ff",
        "primary-container": "#2563eb",
        "on-tertiary-fixed-variant": "#7d2d00",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#bc4800",
        "on-background": "#191b23",
        "tertiary": "#943700",
        "on-tertiary-container": "#ffede6",
        "surface-container-high": "#e7e7f3",
        "on-secondary-fixed-variant": "#3f465c",
        "primary": "#004ac6",
        "surface-dim": "#d9d9e5",
        "surface-container-low": "#f3f3fe",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-tertiary-fixed": "#360f00",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "primary-fixed": "#dbe1ff",
        "surface-tint": "#0053db",
        "on-surface-variant": "#434655",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e2ed",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "on-surface": "#191b23",
        "on-primary-fixed": "#00174b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-columns": "0px",
        "margin-page": "24px",
        "unit": "4px",
        "sidebar-width": "240px",
        "list-width": "320px",
        "reader-max-width": "800px"
      },
      fontFamily: {
        "reader-h1": ["Inter"],
        "list-preview": ["Inter"],
        "reader-code": ["Space Grotesk"],
        "reader-body": ["Newsreader"],
        "list-title": ["Inter"],
        "nav-item": ["Inter"],
        "meta-label": ["Inter"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
